create or replace TABLE NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.BRADESCO_CADASTRO as
(

-- script juncao tabelas bradesco
 with CADASTRO_TITULAR as (
    SELECT 
 '1' AS CODIGO_OPERADORA
 ,'BRADESCO' AS NOME_OPERADORA
 ,TITULAR.TIPO_REGISTRO AS CODIGO_PARENTESCO
 ,    CASE
        WHEN TITULAR.TIPO_REGISTRO=2 THEN 'TITULAR'
        WHEN TITULAR.TIPO_REGISTRO=3 THEN 'DEPENDENTE'
        ELSE 'DEMAIS'
    END AS DESCRICAO_ELEGIBILIDADE
,TITULAR.CODIGO_EMPRESA_OPERADORA as CODIGO_LOCAL_EMPRESA_OPERADORA
,TITULAR.CODIGO_FAMILIA
,TITULAR.NOME_BENEFICIARIO
,TITULAR.CODIGO_MATRICULA
,TITULAR.DESCRICAO_GENERO
,TITULAR.DESCRICAO_ESTADO_CIVIL
,TITULAR.CPF AS CODIGO_CPF_DEPENDENTE
,TITULAR.CPF AS CODIGO_CPF_TITULAR
,TITULAR.NOME_CARGO
,TITULAR.CODIGO_PLANO
,TITULAR.CODIGO_MATRICULA_ESPECIAL
,TITULAR.DATA_NASCIMENTO
,TITULAR.DATA_ADMISSAO
,TITULAR.DATA_INCLUSAO_PLANO
,TITULAR.DATA_REATIVACAO_PLANO
,TITULAR.REGIAO
,TITULAR.DATA_EXCLUSAO_PLANO
,NOM_MAE.NOME_MAE
,NOM_MAE.CODIGO_CARTEIRINHA as CODIGO_BENEFICIARIO
,APOLICE.CODIGO_CONTRATO
,APOLICE.DATA_REFERENCIA
,APOLICE.DATA_PROCESSAMENTO
,TITULAR.ETL_SOURCE_FILE_NAME
,TITULAR.ETL_SOURCE_ZIP_NAME
,TITULAR.RUN_ID
,TITULAR.DATE_TIME_LOAD_STG
,TITULAR.SOURCE_FILE_NAME_LINE_NUMBER
,TITULAR.DATE_TIME_STG_TO_SILVER
FROM NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.DATABRICKS_SILVER.CADASTRO_2_BRADESCO TITULAR
LEFT JOIN NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.DATABRICKS_SILVER.CADASTRO_5_BRADESCO NOM_MAE
ON TITULAR.CODIGO_FAMILIA = NOM_MAE.CODIGO_FAMILIA
AND TITULAR.ETL_SOURCE_FILE_NAME = NOM_MAE.ETL_SOURCE_FILE_NAME
AND TITULAR.ETL_SOURCE_ZIP_NAME = NOM_MAE.ETL_SOURCE_ZIP_NAME
LEFT JOIN  NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.DATABRICKS_SILVER.CADASTRO_1_BRADESCO APOLICE
ON  TITULAR.ETL_SOURCE_FILE_NAME = APOLICE.ETL_SOURCE_FILE_NAME
AND TITULAR.ETL_SOURCE_ZIP_NAME = APOLICE.ETL_SOURCE_ZIP_NAME

WHERE 1=1
--AND TITULAR.NOME_BENEFICIARIO = 'ALEXANDRE FELIPE COBO'

)

,
CADASTRO_DEPENDENTE as (
SELECT 
 '1' AS CODIGO_OPERADORA
 ,'BRADESCO' AS NOME_OPERADORA
 ,DEPENDENTE.TIPO_REGISTRO AS CODIGO_PARENTESCO
 ,    CASE
        WHEN DEPENDENTE.TIPO_REGISTRO=2 THEN 'TITULAR'
        WHEN DEPENDENTE.TIPO_REGISTRO=3 THEN 'DEPENDENTE'
        ELSE 'DEMAIS'
    END AS DESCRICAO_ELEGIBILIDADE
,DEPENDENTE.CODIGO_EMPRESA_OPERADORA as CODIGO_LOCAL_EMPRESA_OPERADORA
,DEPENDENTE.CODIGO_FAMILIA
,DEPENDENTE.NOME_BENEFICIARIO
,TITULAR.CODIGO_MATRICULA
,DEPENDENTE.DESCRICAO_GENERO
,DEPENDENTE.CODIGO_ESTADO_CIVIL
,DEPENDENTE.CPF AS CODIGO_CPF_DEPENDENTE
,TITULAR.CPF AS CODIGO_CPF_TITULAR
,'' AS NOME_CARGO
,TITULAR.CODIGO_PLANO
,TITULAR.CODIGO_MATRICULA_ESPECIAL
,DEPENDENTE.DATA_NASCIMENTO
,TITULAR.DATA_ADMISSAO
,DEPENDENTE.DATA_INCLUSAO_PLANO
,DEPENDENTE.DATA_REATIVACAO_PLANO
,TITULAR.REGIAO
,DEPENDENTE.DATA_EXCLUSAO_PLANO
,DEPENDENTE.NOME_MAE
,DEPENDENTE.CODIGO_CARTEIRINHA as CODIGO_BENEFICIARIO
,APOLICE.CODIGO_CONTRATO
,APOLICE.DATA_REFERENCIA
,APOLICE.DATA_PROCESSAMENTO
,DEPENDENTE.ETL_SOURCE_FILE_NAME
,DEPENDENTE.ETL_SOURCE_ZIP_NAME
,DEPENDENTE.RUN_ID
,DEPENDENTE.DATE_TIME_LOAD_STG
,DEPENDENTE.SOURCE_FILE_NAME_LINE_NUMBER
,DEPENDENTE.DATE_TIME_STG_TO_SILVER
FROM NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.DATABRICKS_SILVER.CADASTRO_3_BRADESCO DEPENDENTE
LEFT JOIN NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.DATABRICKS_SILVER.CADASTRO_2_BRADESCO TITULAR
ON DEPENDENTE.CODIGO_FAMILIA = TITULAR.CODIGO_FAMILIA
AND DEPENDENTE.ETL_SOURCE_FILE_NAME = TITULAR.ETL_SOURCE_FILE_NAME
AND DEPENDENTE.ETL_SOURCE_ZIP_NAME = TITULAR.ETL_SOURCE_ZIP_NAME
LEFT JOIN  NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.DATABRICKS_SILVER.CADASTRO_1_BRADESCO APOLICE
ON  TITULAR.ETL_SOURCE_FILE_NAME = APOLICE.ETL_SOURCE_FILE_NAME
AND TITULAR.ETL_SOURCE_ZIP_NAME = APOLICE.ETL_SOURCE_ZIP_NAME
WHERE 1=1
--and DEPENDENTE.NOME_BENEFICIARIO = 'MARIA FERNANDA AFFONSO COBO'

)


SELECT 
    CODIGO_OPERADORA
    ,NOME_OPERADORA
    ,CODIGO_PARENTESCO
    ,DESCRICAO_ELEGIBILIDADE
    ,CODIGO_LOCAL_EMPRESA_OPERADORA
    ,CODIGO_FAMILIA
    ,NOME_BENEFICIARIO
    ,CODIGO_MATRICULA
    ,DESCRICAO_GENERO
    ,DESCRICAO_ESTADO_CIVIL
    ,CODIGO_CPF_DEPENDENTE
    ,CODIGO_CPF_TITULAR
    ,NOME_CARGO
    ,CODIGO_PLANO
    ,CODIGO_MATRICULA_ESPECIAL
    ,DATA_NASCIMENTO
    ,DATA_ADMISSAO
    ,DATA_INCLUSAO_PLANO
    ,DATA_REATIVACAO_PLANO
    ,REGIAO
    ,DATA_EXCLUSAO_PLANO
    ,NOME_MAE
    ,CODIGO_BENEFICIARIO
    ,CODIGO_CONTRATO
    ,DATA_REFERENCIA
    ,DATA_PROCESSAMENTO
    ,ETL_SOURCE_FILE_NAME
    ,ETL_SOURCE_ZIP_NAME
    ,RUN_ID
    ,DATE_TIME_LOAD_STG
    ,SOURCE_FILE_NAME_LINE_NUMBER
    ,DATE_TIME_STG_TO_SILVER
    ,GETDATE() AS DATE_TIME_SILVER_TO_GOLD
 FROM CADASTRO_TITULAR

UNION ALL


SELECT 
    CODIGO_OPERADORA
    ,NOME_OPERADORA
    ,CODIGO_PARENTESCO
    ,DESCRICAO_ELEGIBILIDADE
    ,CODIGO_LOCAL_EMPRESA_OPERADORA
    ,CODIGO_FAMILIA
    ,NOME_BENEFICIARIO
    ,CODIGO_MATRICULA
    ,DESCRICAO_GENERO
    ,CODIGO_ESTADO_CIVIL AS DESCRICAO_ESTADO_CIVIL
    ,CODIGO_CPF_DEPENDENTE
    ,CODIGO_CPF_TITULAR
    ,NOME_CARGO
    ,CODIGO_PLANO
    ,CODIGO_MATRICULA_ESPECIAL
    ,DATA_NASCIMENTO
    ,DATA_ADMISSAO
    ,DATA_INCLUSAO_PLANO
    ,DATA_REATIVACAO_PLANO
    ,REGIAO
    ,DATA_EXCLUSAO_PLANO
    ,NOME_MAE
    ,CODIGO_BENEFICIARIO
    ,CODIGO_CONTRATO
    ,DATA_REFERENCIA
    ,DATA_PROCESSAMENTO
    ,ETL_SOURCE_FILE_NAME
    ,ETL_SOURCE_ZIP_NAME
    ,RUN_ID
    ,DATE_TIME_LOAD_STG
    ,SOURCE_FILE_NAME_LINE_NUMBER
    ,DATE_TIME_STG_TO_SILVER
    ,GETDATE() AS DATE_TIME_SILVER_TO_GOLD
 FROM CADASTRO_DEPENDENTE


)

;
-- GRANTS PARA CONCEDER PRIVILÉGIO DE LEITURA AS ROLES QUE O POWERBI UTILIZA
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;

/* FIM DO SCRIPT */