create or replace TABLE NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.CADASTRO_UNIFICADO (
    CODIGO_OPERADORA VARCHAR(16777216),
    NOME_OPERADORA VARCHAR(16777216),
    CODIGO_CONTRATO VARCHAR(16777216),
	--CODIGO_GRUPO_ECONOMICO_OPERADORA VARCHAR(16777216),
	CODIGO_LOCAL_EMPRESA_OPERADORA VARCHAR(16777216),
	NOME_LOCAL_EMPRESA_OPERADORA VARCHAR(16777216),
	--CODIGO_PRODUTO_OPERADORA VARCHAR(16777216),
	--CODIGO_LOTACAO VARCHAR(16777216),
	--NOME_LOTACAO VARCHAR(16777216),
	--UF_EMPRESA VARCHAR(16777216),
	CODIGO_BENEFICIARIO VARCHAR(16777216),
	CODIGO_FAMILIA VARCHAR(16777216),
	--CODIGO_CLASSIFICACAO_BENEFICIARIO VARCHAR(16777216),
	--CODIGO_IDENTIFICADOR_TITULAR VARCHAR(16777216),
	NOME_BENEFICIARIO VARCHAR(16777216),
	CODIGO_CPF_TITULAR VARCHAR(16777216),
	CODIGO_CPF_DEPENDENTE VARCHAR(16777216),
	DATA_NASCIMENTO DATE,
	DESCRICAO_GENERO VARCHAR(16777216),
	CODIGO_PARENTESCO VARCHAR(16777216),
	--DESCRICAO_PARENTESCO VARCHAR(16777216),
	NOME_MAE VARCHAR(16777216),
	CODIGO_PLANO VARCHAR(16777216),
	--DESCRICAO_PLANO VARCHAR(16777216),
	--TIPO_ACOMODACAO_PLANO VARCHAR(16777216),
	DATA_INCLUSAO_PLANO DATE,
	DATA_EXCLUSAO_PLANO DATE,
	--CODIGO_PERMANECNCIA_PLANO VARCHAR(16777216),
	--DESCRICAO_PERMANECNCIA_PLANO VARCHAR(16777216),
	DESCRICAO_ELEGIBILIDADE VARCHAR(16777216),
	--SITUACAO_BENEFICIARIO VARCHAR(16777216),
	--INDICA_BENEFICIARIO_REMIDO VARCHAR(16777216),
	--DATA_DEMISSAO_APOSENADO DATE,
	--DATA_LIMITE_PERMANENCIA_PLANO DATE,
	--CODIGO_SETOR_BENEFICIARIO_EMPRESA VARCHAR(16777216),
	--DESCRICAO_SETOR_BENEFICIARIO_EMPRESA VARCHAR(16777216),
	--CODIGO_CNS VARCHAR(16777216),
	DATA_REFERENCIA DATE,
	ETL_SOURCE_FILE_NAME VARCHAR(16777216),
	ETL_SOURCE_ZIP_NAME VARCHAR(16777216),
	RUN_ID VARCHAR(16777216),
	DATE_TIME_LOAD_STG TIMESTAMP_NTZ(9),
	SOURCE_FILE_NAME_LINE_NUMBER NUMBER(38,0),
	DATE_TIME_STG_TO_SILVER TIMESTAMP_NTZ(9),
    DATE_TIME_SILVER_TO_GOLD TIMESTAMP_NTZ(9)
)

AS


SELECT
 '9' AS CODIGO_OPERADORA
 ,'SULAMERICA' AS NOME_OPERADORA
,CODIGO_CONTRATO
,CODIGO_LOCAL_EMPRESA_OPERADORA
,NOME_LOCAL_EMPRESA_OPERADORA
,CODIGO_BENEFICIARIO
,CODIGO_FAMILIA
,NOME_BENEFICIARIO
,CODIGO_CPF_TITULAR
,CODIGO_CPF_DEPENDENTE
,DATA_NASCIMENTO
,DESCRICAO_GENERO
,CODIGO_PARENTESCO
,NOME_MAE
,CODIGO_PLANO
,DATA_INCLUSAO_PLANO
,DATA_EXCLUSAO_PLANO
,DESCRICAO_ELEGIBILIDADE
,DATA_REFERENCIA
,ETL_SOURCE_FILE_NAME
,ETL_SOURCE_ZIP_NAME
,RUN_ID
,DATE_TIME_LOAD_STG
,SOURCE_FILE_NAME_LINE_NUMBER
,DATE_TIME_STG_TO_SILVER
,GETDATE() AS DATE_TIME_SILVER_TO_GOLD
FROM NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.DATABRICKS_SILVER.CADASTRO_SULAMERICA

UNION ALL


SELECT
CODIGO_OPERADORA
, NOME_OPERADORA
,CODIGO_CONTRATO
,CODIGO_LOCAL_EMPRESA_OPERADORA
,'' as NOME_LOCAL_EMPRESA_OPERADORA
,CODIGO_BENEFICIARIO
,CODIGO_FAMILIA
,NOME_BENEFICIARIO
,CODIGO_CPF_TITULAR
,CODIGO_CPF_DEPENDENTE
,DATA_NASCIMENTO
,DESCRICAO_GENERO
,CODIGO_PARENTESCO
,NOME_MAE
,CODIGO_PLANO
,DATA_INCLUSAO_PLANO
,DATA_EXCLUSAO_PLANO
,DESCRICAO_ELEGIBILIDADE
,DATA_REFERENCIA
,ETL_SOURCE_FILE_NAME
,ETL_SOURCE_ZIP_NAME
,RUN_ID
,DATE_TIME_LOAD_STG
,SOURCE_FILE_NAME_LINE_NUMBER
,DATE_TIME_STG_TO_SILVER
,DATE_TIME_SILVER_TO_GOLD
FROM NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.BRADESCO_CADASTRO




;
-- GRANTS PARA CONCEDER PRIVILÉGIO DE LEITURA AS ROLES QUE O POWERBI UTILIZA
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;

/* FIM DO SCRIPT */