create or replace view GOLD.EV_PREM(
	CHAVE_JOIN,
	PRE_CHAVE,
	DT_REFR,
	CD_OPRD,
	CD_APLC,
	CD_EMPR,
	CD_PLNO,
	CD_EMPR_GRPO,
	FL_SEXO,
	NR_IDDE,
	NM_FAIX_ETRA,
	NM_CATG_USRO,
	CD_DIVISAO,
	PLANO_AON_2,
	CODIGO_GRUPO_ECONOMICO_OPERADORA,
	VL_PREM,
	VL_ACRT,
	VL_FRNQ,
	VL_APRT,
	VL_CO_PART,
	QT_USRO
) as
WITH HASH_PREMIO AS (
    SELECT
        DATA_REFERENCIA AS DT_REFR,
        CODIGO_OPERADORA AS CD_OPRD,
        CODIGO_CONTRATO AS CD_APLC,
        CODIGO_EMPRESA AS CD_EMPR,
        CODIGO_PLANO AS CD_PLNO,
        CODIGO_LOCAL_EMPRESA_OPERADORA AS CD_EMPR_GRPO,
        DESCRICAO_GENERO as FL_SEXO,
        IDADE_BENEFICIARIO as NR_IDDE,
        FAIXA_ETARIA as NM_FAIX_ETRA,
        CODIGO_TIPO_BENEFICIARIO as NM_CATG_USRO,
        0 as CD_DIVISAO, -- CAMPO JBS
        PLANO_AON_2,
        CODIGO_GRUPO_ECONOMICO_OPERADORA,
        VALOR_PAGO AS VL_PREM,
        VALOR_ACERTO as VL_ACRT,
        VALOR_FRANQUIA as VL_FRNQ,
        VALOR_APORTE as VL_APRT,
        VALOR_COPARTICIPACAO as VL_CO_PART,
        QUANTIDADE_BENEFICIARIO_ATIVO as QT_USRO
    FROM
        GOLD.TESTE_PREMIO_UNIFICADO
)
SELECT
    GOLD.FN_CHAVE_JOIN(
        DT_REFR,
        CD_OPRD,
        CD_EMPR,
        CD_PLNO,
        CD_APLC,
        CD_EMPR_GRPO,
        FL_SEXO,
        NR_IDDE,
        NM_FAIX_ETRA,
        NM_CATG_USRO,
        CD_DIVISAO,
        PLANO_AON_2
    ) as CHAVE_JOIN,
    GOLD.FN_PRE_CHAVE_JOIN(
        DT_REFR,
        CD_OPRD,
        CD_EMPR,
        CD_PLNO,
        CD_APLC,
        CD_EMPR_GRPO,
        FL_SEXO,
        NR_IDDE,
        NM_FAIX_ETRA,
        NM_CATG_USRO,
        CD_DIVISAO,
        PLANO_AON_2
    ) as PRE_CHAVE,
    *
FROM
    HASH_PREMIO
;