/*
VIEW: EV_UTLZ
OBJETIVO: DADOS DE UTILIZACAO DO PLANO. 
AUTOR: DANILO MELO
ALTERAÇOES:
26-03-2024 - VERSÃO INICIAL
 */
create or replace view GOLD.EV_UTLZ(
	CHAVE_JOIN,
	PRE_CHAVE,
    ID_USRO,
    CD_USRO1,
    CD_USRO2,
	CD_OPRD,
	CD_EMPR,
	DT_REFR,
	COD_PRESTADOR,
	NM_LCAL_UTLZ,
	NM_EVNT,
	NM_ESPC,
	CD_SRVC,
	DS_SRVC,
	NM_REDE_RMBL,
	CD_USRO,
	NM_USRO,
	DT_INICIO_INTERNACAO,
	ID_INTR_AON,
	DT_ATND,
	VL_PAGO_EVNT,
	VL_RCBO,
	VL_CO_PART,
	QT_SRVC,
	CD_DIVISAO,
	ID_TER_COMPL_AON,
	ID_PS_AON,
	NM_EVNT2,
	NM_LCAL_UTLZ2,
	DS_SRVC2,
	CD_TUSS,
	CD_CBHPM,
	PROC_PRINC,
	CATEGORIA,
	TIPO_INTERNACAO,
	REGIME_DIARIA,
	TIPO_ENTRADA,
	CRONICOS,
	GRUPO,
	ARH_COD,
	CD_APLC,
	CD_PLNO,
	CD_EMPR_GRPO,
	FL_SEXO,
	NR_IDDE,
	NM_FAIX_ETRA,
	NM_CATG_USRO,
	PLANO_AON_2
) as 
TABELA_UTILIZACAO as(
	SELECT 
		FN_CREATE_ID_USRO(NOME_BENEFICIARIO , DATA_NASCIMENTO ) as ID_USRO
		,FN_CREATE_COD_USRO(NOME_BENEFICIARIO , DATA_NASCIMENTO , 1 )  as CD_USRO1
		,FN_CREATE_COD_USRO(NOME_BENEFICIARIO , DATA_NASCIMENTO , 2 )   AS CD_USRO2 
		,A.CODIGO_OPERADORA as CD_OPRD
		,A.CODIGO_EMPRESA
		,A.DATA_REFERENCIA as DT_REFR
		,A.CODIGO_CNPJ_PRESTADOR as COD_PRESTADOR
		,A.NOME_PRESTADOR as NM_LCAL_UTLZ
		,A.NOME_EVENTO as NM_EVNT
		, DESCRICAO_ESPECIALIDADE AS NM_ESPC
		,A.CODIGO_PROCEDIMENTO AS CD_SRVC
		,A.DESCRICAO_PROCEDIMENTO AS DS_SRVC
		,A.TIPO_ATENDIMENTO AS NM_REDE_RMBL
		,A.CODIGO_BENEFICIARIO as CD_USRO 
		,A.NOME_BENEFICIARIO AS NM_USRO 
		,A.INICIO_INTERNACAO AS DT_INICIO_INTERNACAO
		,A.CHAVE_INTERNACAO_AON AS ID_INTR_AON
		,A.DATA_PROCEDIMENTO AS DT_ATND
		,A.VALOR_PAGO AS VL_PAGO_EVNT
		, 0 AS VL_RCBO -- parece específico para Sulamerica
		-- , VALOR_RECIBO AS VL_RCBO -- confirmar nome original
		, A.VALOR_COPARTICIPACAO  AS VL_CO_PART
		, A.QUANTIDADE_PROCEDIMENTO AS QT_SRVC
		, '00' AS CD_DIVISAO -- SOMENTE PARA JBS E FEMSA
		, A.CHAVE_TERAPIA_COMPLEXA_AON AS ID_TER_COMPL_AON 
		, A.CHAVE_PRONTO_SOCORRO_AON AS ID_PS_AON
		, A.NM_EVNT2 AS NM_EVNT2 
		, A.NOME_PRESTADOR AS NM_LCAL_UTLZ2 
		, A.DS_SRVC_2  AS DS_SRVC2
		, A.COD_TUSS   AS CD_TUSS
		, A.COD_CBHPM  AS CD_CBHPM
		, A.PROC_PRINC   AS PROC_PRINC
		, A.CATEGORIA  AS CATEGORIA
		, A.TIPO_INTERNACAO  AS TIPO_INTERNACAO
		, A.REGIME_DIARIA   AS REGIME_DIARIA
		, A.TIPO_ENTRADA_INTERNACAO AS TIPO_ENTRADA
		, A.CRONICO AS CRONICOS
		, A.GRUPO  AS GRUPO
		/* CAMPOS COMENTADOS PARA PERMITIR QUE O BUG DE CATEGORIA SEJA RESOLVIDO NA TABELA DE CLASSIFICACAO */
		/* 
		, IFNULL(A.DS_SRVC_ABREVIADA , PROCEDIMENTOS_RANK.DS_SRVC_ABREVIADA)  AS DS_SRVC2
		, IFNULL(A.COD_TUSS , PROCEDIMENTOS_RANK.COD_TUSS)  AS CD_TUSS
		, IFNULL(A.COD_CBHPM , PROCEDIMENTOS_RANK.COD_CBHPM)  AS CD_CBHPM
		, IFNULL(A.PROC_PRINC , PROCEDIMENTOS_RANK.PROC_PRINC)  AS PROC_PRINC
		, IFNULL(A.CATEGORIA , PROCEDIMENTOS_RANK.CATEGORIA)  AS CATEGORIA
		, IFNULL(A.TIPO_INTERNACAO , PROCEDIMENTOS_RANK.TIPO_INTERNACAO)  AS TIPO_INTERNACAO
		, IFNULL(A.REGIME_DIARIA , PROCEDIMENTOS_RANK.REGIME_DIARIA)  AS REGIME_DIARIA
		, TIPO_ENTRADA_INTERNACAO AS TIPO_ENTRADA
		, IFNULL(A.CRONICO , PROCEDIMENTOS_RANK.CRONICO)  AS CRONICOS
		, IFNULL(A.GRUPO , PROCEDIMENTOS_RANK.GRUPO)  AS GRUPO
		*/
		, A.CODIGO_PLANO AS CD_PLNO -- como o codigo original é utilizado no left join para trazer campo "observacao", nao tem diferença usar o original
		, A.CODIGO_CONTRATO as CD_APLC
		, A.CODIGO_LOCAL_EMPRESA_OPERADORA as CD_EMPR_GRPO
		, A.DESCRICAO_GENERO AS FL_SEXO
		, A.IDADE_BENEFICIARIO as NR_IDDE
		, A.FAIXA_ETARIA AS NM_FAIX_ETRA
		,CASE
			WHEN DESCRICAO_ELEGIBILIDADE = 'TITULAR' THEN 'T'
			WHEN DESCRICAO_ELEGIBILIDADE = 'DEPENDENTE' THEN 'D'
			WHEN DESCRICAO_ELEGIBILIDADE IS NOT NULL THEN 'D'
		END 
		AS NM_CATG_USRO   
		,A.OBSERVACAO as PLANO_AON_2 
		, 0 as ARH_COD -- somente para a empresa FEMSA KOF
	FROM GOLD.TESTE_SINISTRO_UNIFICADO  A 
)
/* SELECT FINAL COM MONTAGEM DOS CAMPOS CHAVE_JOIN E PRE_CHAVE */
SELECT 
    GOLD.FN_CHAVE_JOIN(
        DT_REFR,
        CD_OPRD,
        CD_EMPR,
        CD_PLNO,
        CD_APLC,
        CD_EMPR_GRPO,
        FL_SEXO,
        NR_IDDE,
        NM_FAIX_ETRA,
        NM_CATG_USRO,
        CD_DIVISAO,
        PLANO_AON_2
    ) as CHAVE_JOIN,
    GOLD.FN_PRE_CHAVE_JOIN(
        DT_REFR,
        CD_OPRD,
        CD_EMPR,
        CD_PLNO,
        CD_APLC,
        CD_EMPR_GRPO,
        FL_SEXO,
        NR_IDDE,
        NM_FAIX_ETRA,
        NM_CATG_USRO,
        CD_DIVISAO,
        PLANO_AON_2
    ) as PRECHAVE,
	, ID_USRO
	, CD_USRO1
	, CD_USRO2
	, CD_OPRD
	, CD_EMPR
	, DT_REFR
	, COD_PRESTADOR
	, NM_LCAL_UTLZ
	, NM_EVNT
	, NM_ESPC
	, CD_SRVC
	, DS_SRVC
	, NM_REDE_RMBL
	, CD_USRO
	, NM_USRO
	, DT_INICIO_INTERNACAO
	, ID_INTR_AON
	, DT_ATND
	, VL_PAGO_EVNT
	, VL_RCBO
	, VL_CO_PART
	, QT_SRVC
	, CD_DIVISAO
	, ID_TER_COMPL_AON
	, ID_PS_AON
	, NM_EVNT2
	, NM_LCAL_UTLZ2
	, DS_SRVC2
	, CD_TUSS
	, CD_CBHPM
	, PROC_PRINC
	, CATEGORIA
	, TIPO_INTERNACAO
	, REGIME_DIARIA
	, TIPO_ENTRADA
	, CRONICOS
	, GRUPO
	,ARH_COD
	,CD_APLC
	,CD_PLNO
	,CD_EMPR_GRPO
	,FL_SEXO
	,NR_IDDE
	,NM_FAIX_ETRA
	, NM_CATG_USRO
	,PLANO_AON_2
from TABELA_UTILIZACAO
;
