/*
FUNCTION: CHAVE_JOIN
OBJETIVO: PADRONIZAR CRIACAO DE UMA CHAVE JOIN ATRAVES DE MULTIPLAS TABELAS
 */

CREATE OR REPLACE FUNCTION NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.FN_CHAVE_JOIN(
    "DT_REFR" DATE,
    "CD_OPRD" VARCHAR,
    "CD_EMPR" VARCHAR,
    "CD_PLNO" VARCHAR,
    "CD_APLC" VARCHAR,
    "CD_EMPR_GRPO" VARCHAR,
    "FL_SEXO" VARCHAR,
    "NR_IDDE" INTEGER,
    "NM_FAIX_ETRA" VARCHAR,
    "NM_CATG_USRO" VARCHAR,
    "CD_DIVISAO" VARCHAR,
    "PLANO_AON_2" VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS $$
SELECT
    HASH(
        CONCAT(
            DT_REFR
            ,CD_OPRD
            ,CD_EMPR
            ,CD_PLNO
            ,CD_APLC
            ,CD_EMPR_GRPO
            ,FL_SEXO
            ,NR_IDDE
            ,NM_FAIX_ETRA
            ,NM_CATG_USRO
            ,CD_DIVISAO
            ,PLANO_AON_2
        )
    )
$$
;