
CREATE OR REPLACE FUNCTION NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.FN_CREATE_ID_USRO(
   NOME_BENEFICIARIO STRING, DATA_NASCIMENTO DATETIME)
RETURNS NUMBER 
 LANGUAGE SQL
  AS  '
SELECT
HASH(
        CONCAT(
            SUBSTR(SPLIT_PART(FN_REPLACE_NAMES(NOME_BENEFICIARIO), '' '', 1), 1, 12), --primeiro nome até 12 caracteres
            SUBSTR(SPLIT_PART(FN_REPLACE_NAMES(NOME_BENEFICIARIO), '' '', 2),1,3), -- segundo nome até 3 caracteres
            SUBSTR(SPLIT_PART(FN_REPLACE_NAMES(NOME_BENEFICIARIO), '' '', 3),1,3),-- terceiro nome até 3 caracteres
            SUBSTR(CAST(DATA_NASCIMENTO as VARCHAR), 3, 2),-- ano do nascimento yy
            SUBSTR(CAST(DATA_NASCIMENTO as VARCHAR), 6, 2),-- mes do nascimento mm
            SUBSTR(CAST(DATA_NASCIMENTO as VARCHAR), 9, 2)) --dia do nascimento dd
    )

  ';                                   
;

-- GRANTS PARA CONCEDER PRIVILÉGIO DE LEITURA AS ROLES QUE O POWERBI UTILIZA
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;
