

/*
FUNCTION: NORMALIZE_MONEY
OBJETIVO: MANTER COMPATIBILIDADE DOS DADOS DO SAS 
AUTOR: DANILO MELO
ALTERAÇOES:
26-03-2024 - VERSÃO INICIAL
 */


CREATE OR REPLACE FUNCTION NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.NORMALIZE_MONEY
("VL" VARCHAR(16777216)) 
RETURNS NUMBER(38,0) LANGUAGE SQL 
AS 'CAST(replace(replace(vl,''.'', ''''), '','', ''.'') as number(10,2))';


-- GRANTS PARA CONCEDER PRIVILÉGIO DE LEITURA AS ROLES QUE O POWERBI UTILIZA
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;
