

/*
FUNCTION: FN_REPLACE_NAMES
OBJETIVO: NORMALIZAR OS CAMPOS DE NOME DO USUARIO A PARTIR DE REGRAS SAS
AUTOR: DANILO MELO
ALTERAÇOES:
26-03-2024 - VERSÃO INICIAL
 */

CREATE OR REPLACE FUNCTION NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.FN_SUBTRACT_MONTH(
    DATA_REF DATETIME)
RETURNS DATETIME 
 LANGUAGE SQL
  AS  '

SELECT DATEADD(MONTH, - 1 , DATA_REF)

  ';                                   
;

-- GRANTS PARA CONCEDER PRIVILÉGIO DE LEITURA AS ROLES QUE O POWERBI UTILIZA
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;
