INSERT INTO NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.REFATORACAO.SULAMERICA_CADASTRO (

SELECT 
	CODIGO_CONTRATO ,
	CODIGO_GRUPO_ECONOMICO_OPERADORA ,
	CODIGO_LOCAL_EMPRESA_OPERADORA ,
	NOME_LOCAL_EMPRESA_OPERADORA ,
	CODIGO_PRODUTO_OPERADORA ,
	CODIGO_LOTACAO ,
	NOME_LOTACAO ,
	UF_EMPRESA ,
	CODIGO_BENEFICIARIO ,
	CODIGO_FAMILIA ,
	CODIGO_CLASSIFICACAO_BENEFICIARIO ,
	CODIGO_IDENTIFICADOR_TITULAR ,
	NOME_BENEFICIARIO ,
	CODIGO_CPF_TITULAR ,
	CODIGO_CPF_DEPENDENTE ,
	DATA_NASCIMENTO ,
	DESCRICAO_GENERO ,
	CODIGO_PARENTESCO ,
	DESCRICAO_PARENTESCO ,
	NOME_MAE ,
	CODIGO_PLANO ,
	DESCRICAO_PLANO ,
	TIPO_ACOMODACAO_PLANO ,
	DATA_INCLUSAO_PLANO ,
	DATA_EXCLUSAO_PLANO ,
	CODIGO_PERMANECNCIA_PLANO ,
	DESCRICAO_PERMANECNCIA_PLANO ,
	DESCRICAO_ELEGIBILIDADE ,
	SITUACAO_BENEFICIARIO ,
	INDICA_BENEFICIARIO_REMIDO ,
	DATA_DEMISSAO_APOSENADO ,
	DATA_LIMITE_PERMANENCIA_PLANO ,
	CODIGO_SETOR_BENEFICIARIO_EMPRESA ,
	DESCRICAO_SETOR_BENEFICIARIO_EMPRESA ,
	CODIGO_CNS ,
	'04/01/2023' as DATA_REFERENCIA ,
	ETL_SOURCE_FILE_NAME ,
	'SULAMERICA_CADASTRO_202212.zip' as ETL_SOURCE_ZIP_NAME ,
	RUN_ID ,
	DATE_TIME ,
	SOURCE_FILE_NAME_LINE_NUMBER 
FROM NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.REFATORACAO.SULAMERICA_CADASTRO
    WHERE 1=1
and ETL_SOURCE_FILE_NAME IN ('REN0.txt','RNT1.txt')
and ETL_SOURCE_ZIP_NAME = 'SULAMERICA_CADASTRO_202308.zip'
and DATE_TIME = '2024-05-06 20:05:40'

)