create or replace view GOLD.TB_USRO(
	ID_USRO,
	NM_USRO,
	DT_NSCM,
	CD_EMPR,
	CD_OPRD,
	NM_USRO_COD,
	IDADE,
	NOME_EMPRESA,
	CD_USRO1,
    CD_USRO2,
	ARH_COD,
	GRUPO,
	NM_CATG_USRO,
	FL_SEXO,
	CPF_USRO,
	CD_MATR,
	CD_MATR_ESPC,
	DT_ADMS,
	DT_EXCL,
	STATUS,
	QT_DIAS_PLANO,
	DT_UREF,
	MES,
	ANO,
	DATA_REFERENCIA
) as
SELECT
    DISTINCT     
    FN_CREATE_ID_USRO(NOME_BENEFICIARIO , DATA_NASCIMENTO ) as ID_USRO,
    NOME_BENEFICIARIO AS NM_USRO,
    DATA_NASCIMENTO AS DT_NSCM,
    CODIGO_EMPRESA AS CD_EMPR,
    A.CODIGO_OPERADORA as CD_OPRD,
    FN_REPLACE_NAMES(NM_USRO) as NM_USRO_COD,
    IDADE_BENEFICIARIO AS IDADE,
    LABEL_EMPRESA AS NOME_EMPRESA,
    FN_CREATE_COD_USRO(NOME_BENEFICIARIO , DATA_NASCIMENTO , 1 )  as CD_USRO1,
    FN_CREATE_COD_USRO(NOME_BENEFICIARIO , DATA_NASCIMENTO , 2 )   AS CD_USRO2,            
    0 AS ARH_COD, -- somente para a empresa FEMSA KOF
    0 AS GRUPO, -- (deixar vazio por enquanto) tabela Ana (cod serviço + desc serviço codificada), podemos puxar da classificao????
    CASE
        WHEN DESCRICAO_ELEGIBILIDADE = 'TITULAR' THEN 'T'
        WHEN DESCRICAO_ELEGIBILIDADE = 'DEPENDENTE' THEN 'D'
        WHEN DESCRICAO_ELEGIBILIDADE IS NOT NULL THEN 'D'
    END AS NM_CATG_USRO,
    DESCRICAO_GENERO AS FL_SEXO,
    CODIGO_CPF_DEPENDENTE AS CPF_USRO,
    CD_MATR,
    CODIGO_FAMILIA AS CD_MATR_ESPC,
    DATA_INCLUSAO_PLANO AS DT_ADMS,
    DATA_EXCLUSAO_PLANO AS DT_EXCL,
    STATUS,
    DATEDIFF(DAY, DATA_INCLUSAO_PLANO, DATA_REFERENCIA) AS QT_DIAS_PLANO,
    DATA_REFERENCIA AS DT_UREF,
    MONTH(DATA_REFERENCIA) as mes,
    YEAR(DATA_REFERENCIA) as ano,
    DATA_REFERENCIA
FROM
    GOLD.TESTE_CADASTRO_UNIFICADO A
    ;

-- GRANTS PARA CONCEDER PRIVILÉGIO DE LEITURA AS ROLES QUE O POWERBI UTILIZA
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA GOLD to ROLE nonprod_analyst;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA GOLD to ROLE nonprod_analyst;

