create or replace view GOLD.TB_USRO_CAD(
	CD_OPRD_ARQUIVO,
	CD_OPRD,
	ID_USRO,
	CHAVE_JOIN,
    CD_USRO1,
    CD_USRO2,
	ARH_COD,
	UTLZ,
	EMPRESA,
	CODIGO_BENEFICIARIO,
	DATA_ULTIMA_UTILIZACAO
) as
WITH ULTIMA_UTILIZACAO AS (
    SELECT
        DISTINCT CODIGO_BENEFICIARIO,
        MAX(DATA_PROCEDIMENTO) AS DATA_ULTIMA_UTILIZACAO
    FROM
        GOLD.TESTE_SINISTRO_UNIFICADO
    WHERE
        1 = 1
    group by
        CODIGO_BENEFICIARIO
),
CAMPOS_CADASTRO AS (
    SELECT
        DATA_REFERENCIA as DT_REFR,
        CODIGO_OPERADORA as CD_OPRD,
        CODIGO_EMPRESA AS CD_EMPR,
        CODIGO_PLANO AS CD_PLNO,
        A.CODIGO_CONTRATO AS CD_APLC,
        CODIGO_LOCAL_EMPRESA_OPERADORA AS CD_EMPR_GRPO,
        DESCRICAO_GENERO AS FL_SEXO,
        IDADE_BENEFICIARIO AS NR_IDDE,
        FAIXA_ETARIA AS NM_FAIX_ETRA,
        CASE
            WHEN DESCRICAO_ELEGIBILIDADE = 'TITULAR' THEN 'T'
            WHEN DESCRICAO_ELEGIBILIDADE = 'DEPENDENTE' THEN 'D'
            WHEN DESCRICAO_ELEGIBILIDADE IS NOT NULL THEN 'D'
        END AS NM_CATG_USRO,
        '00' AS CD_DIVISAO, -- SOMENTE PARA JBS E FEMSA
        OBSERVACAO as PLANO_AON_2,
        STATUS,
        CASE
            WHEN STATUS = 'CANCELADO' THEN 0
            ELSE 1
        END AS STATUS_NUMERICO,
        A.NOME_BENEFICIARIO,
        A.DATA_NASCIMENTO,
        A.CODIGO_BENEFICIARIO,
        ULTIMA_UTILIZACAO.DATA_ULTIMA_UTILIZACAO,
        NOME_EMPRESA AS LABEL_EMPRESA
    FROM
        GOLD.TESTE_CADASTRO_UNIFICADO A
)
SELECT
    DISTINCT CD_OPRD as CD_OPRD_ARQUIVO,
    CD_OPRD,
	GOLD.FN_CREATE_ID_USRO(NOME_BENEFICIARIO , DATA_NASCIMENTO ) as ID_USRO,
    GOLD.FN_CHAVE_JOIN(
        DT_REFR,
        CD_OPRD,
        CD_EMPR,
        CD_PLNO,
        CD_APLC,
        CD_EMPR_GRPO,
        FL_SEXO,
        NR_IDDE,
        NM_FAIX_ETRA,
        NM_CATG_USRO,
        CD_DIVISAO,
        PLANO_AON_2
    ) as CHAVE_JOIN,
    GOLD.FN_CREATE_COD_USRO(NOME_BENEFICIARIO , DATA_NASCIMENTO , 1 )  as CD_USRO1,
    GOLD.FN_CREATE_COD_USRO(NOME_BENEFICIARIO , DATA_NASCIMENTO , 2 )   AS CD_USRO2,   
    NULL AS ARH_COD, -- SOMENTE PARA JBS E FEMSA
CASE
        WHEN (DATA_ULTIMA_UTILIZACAO IS NULL) THEN 0
        ELSE 1
    END AS UTLZ,
    LABEL_EMPRESA AS EMPRESA,
    CODIGO_BENEFICIARIO,
    DATA_ULTIMA_UTILIZACAO
FROM
    CAMPOS_CADASTRO;