




create or replace view NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.VW_AUX_EV(

/*
VIEW: VW_AUX_EV
OBJETIVO: MANTER COMPATIBILIDADE COM O POWERBI. REGRAS DE NEGOCIO FORAM IMPLEMENTADAS AS IS
          VIEW ORIGINAL LOCALIZADA DENTRO DO DATABASE NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.FASTVIEW 
          NÃO FORAM FEITAS ALTERACOES NEM REFATORAÇÃO DESSE CODIGO FONTE
AUTOR: DANILO MELO
ALTERAÇOES:
26-03-2024 - VERSÃO INICIAL
 */



	CHAVE_JOIN,
	PRE_CHAVE,
	DT_REFR,
	CD_OPRD_AUX,
	CD_EMPR_AUX,
	CD_DIVISAO,
	CD_PLNO,
	CD_APLC,
	CD_EMPR_GRPO,
	FL_SEXO,
	NR_IDDE,
	NM_FAIX_ETRA,
	NM_CATG_USRO,
	LABEL_OPERADORA,
	LABEL_EMPRESA,
	ARH_COD,
	PLANO_AON2,
	EMPRESA,
	FAIXA_ETARIA,
	GRUPO_ETARIO,
	CHAVE_PLANO,
	CHAVE_EMPRESA,
	NM_OPRD_DP,
	NM_EMPR_DP,
	TP_PGTO,
	PTO_EQLB,
	CD_OPRD,
	NM_OPRD,
	CD_EMPR_EMP,
	NM_EMPR,
	VL_PREM,
	VL_ACRT,
	VL_FRNQ,
	VL_CO_PART_PREM,
	VL_APRT,
	VL_PAGO_EVNT,
	VL_RCBO,
	VL_CO_PART_UTLZ,
	VL_IBNR,
    ORIGEM
) as 




WITH AUX_EMP AS (
SELECT DISTINCT
      AUX_EV.CHAVE_JOIN 
    , AUX_EV.PRE_CHAVE
    , TRY_TO_DATE (AUX_EV.DT_REFR) DT_REFR
    , AUX_EV.CD_OPRD as "CD_OPRD_AUX"
    , AUX_EV.CD_EMPR AS "CD_EMPR_AUX"
    , aux_ev.CD_DIVISAO // adicionado por conta da jbs
    , AUX_EV.CD_PLNO  As CD_PLNO
    , AUX_EV.CD_APLC
    , AUX_EV.CD_EMPR_GRPO
    -- , AUX_EV.FL_SEXO
     --,TRY_TO_NUMBER(AUX_EV.NR_IDDE) as "NR_IDDE" 
    , cast(AUX_EV.NR_IDDE AS integer) as "NR_IDDE" 
    , AUX_EV.NM_FAIX_ETRA
    -- , AUX_EV.NM_CATG_USRO
    , AUX_EV.ARH_COD
    , AUX_EV.PLANO_AON2
    -- , AUX_EV.CODIGO_OPERADORA // NAO TEM NO FASTVIEW_RAW
    -- , AUX_EV.UUID
    -- , AUX_EV.ETL_DT_LOAD_DISCOVERY
    -- , AUX_EV.ETL_SOURCE_FILE_NAME
    -- , AUX_EV.RUN_ID
    , TB_EMPRESAS.LABEL_EMPRESA AS EMPRESA  --AUX_EV.EMPRESA 
    -- , AUX_EV.CD_OPRD_ARQUIVO 
    -- , AUX_EV.ETL_FILE_NAME_INSIDE_ARCHIVE
    , CASE 
        WHEN AUX_EV.CD_OPRD = '2' THEN
        CASE
            WHEN NM_FAIX_ETRA IS NULL THEN 'N/C'
            WHEN NM_FAIX_ETRA = 'ATE 17'     then '00 a 17'
            WHEN NM_FAIX_ETRA = 'DE 18 A 29' then '18 a 29'
            WHEN NM_FAIX_ETRA = 'DE 30 A 39' then '30 a 39'
            WHEN NM_FAIX_ETRA = 'DE 40 A 49' then '40 a 49'
            WHEN NM_FAIX_ETRA = 'DE 50 A 59' then '50 a 59'
            WHEN NM_FAIX_ETRA = 'DE 60 A 69' then '60 a 69'
            WHEN NM_FAIX_ETRA = 'MAIS DE 69' then '70 ou +'
            ELSE 'N/C'
        END
      WHEN AUX_EV.CD_OPRD = '32' THEN
        CASE
            WHEN NM_FAIX_ETRA IS NULL THEN 'N/C'
            WHEN NM_FAIX_ETRA = 'ATE 18' then '00 a 18'
            WHEN NM_FAIX_ETRA = 'DE 19 A 23' then '19 a 23'
            WHEN NM_FAIX_ETRA = 'DE 24 A 28' then '24 a 28'
            WHEN NM_FAIX_ETRA = 'DE 29 A 33' then '29 a 33'
            WHEN NM_FAIX_ETRA = 'DE 34 A 38' then '34 a 38'
            WHEN NM_FAIX_ETRA = 'DE 39 A 43' then '39 a 43'
            WHEN NM_FAIX_ETRA = 'DE 44 A 48' then '44 a 48'
            WHEN NM_FAIX_ETRA = 'DE 49 A 53' then '49 a 53'
            WHEN NM_FAIX_ETRA = 'DE 54 A 58' then '54 a 58'
            WHEN NM_FAIX_ETRA = 'MAIS DE 58' then '59 ou +'
            ELSE 'N/C'
        END
      ELSE
        CASE
            WHEN NR_IDDE IS NULL THEN 'N/C'
            WHEN NR_IDDE <= 18 THEN '00 a 18'
            WHEN NR_IDDE <= 23 then '19 a 23'
            WHEN NR_IDDE <= 28 then '24 a 28'
            WHEN NR_IDDE <= 33 then '29 a 33'
            WHEN NR_IDDE <= 38 then '34 a 38'
            WHEN NR_IDDE <= 43 then '39 a 43'
            WHEN NR_IDDE <= 48 then '44 a 48' 
            WHEN NR_IDDE <= 53 then '49 a 53'
            WHEN NR_IDDE <= 58 then '54 a 58'
            WHEN NR_IDDE >= 59 then '59 ou +'
            ELSE 'N/C'
        END 
    END AS "FAIXA_ETARIA" // REVISAR OPERADORAS 2 E 32 
    , CASE
        -- WHEN NR_IDDE IS NULL THEN 'N/C' // TIREI PORQUE JA CHECA ISSO NO ELSE
        WHEN NR_IDDE >= 65 THEN 'Idosos acima de 65 anos'
        WHEN 
            NR_IDDE >= 10 AND 
            NR_IDDE <= 45 AND
            FL_SEXO = 'F' 
            THEN 'Mulheres em idade fértil'
        ELSE 'N/C' 
    END AS "GRUPO_ETARIO"
    , AUX_EV.CD_EMPR  || '_'||  cast(AUX_EV.CD_PLNO AS string) AS "CHAVE_PLANO"
    , AUX_EV.CD_OPRD  || '_'||  AUX_EV.CD_EMPR AS "CHAVE_EMPRESA"
    , TB_EMPRESAS.NM_OPRD AS "NM_OPRD_DP"
    , TB_EMPRESAS.NM_EMPR AS "NM_EMPR_DP"
    , TB_EMPRESAS.TP_PGTO
    , TB_EMPRESAS.PTO_EQLB

    , CASE 
        WHEN FL_SEXO = 'M' then 'M'
        WHEN FL_SEXO = 'F' then 'F'
        ELSE 'N/C'
     END AS "FL_SEXO"
    , CASE
        WHEN NM_CATG_USRO = 'T' then 'Titular'
        WHEN NM_CATG_USRO = 'D' then 'Dependente'
        else 'N/C'
    END AS "NM_CATG_USRO"

    , TB_EMPRESAS.NM_OPRD || ' (CD_'||  TB_EMPRESAS.CD_OPRD || ')'  AS "LABEL_OPERADORA"
    , TB_EMPRESAS.NM_EMPR || ' (CD_'||  TB_EMPRESAS.CD_EMPR || ')'  AS "LABEL_EMPRESA"
    ,AUX_EV.ORIGEM
    
FROM NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.AUX_EV AUX_EV    
LEFT JOIN NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.TB_EMPRESAS 
    ON ( TB_EMPRESAS.CD_OPRD = AUX_EV.CD_OPRD ) 
    AND (TB_EMPRESAS.CD_EMPR = AUX_EV.CD_EMPR )
)


SELECT DISTINCT
  AUX_EMP.CHAVE_JOIN  
, AUX_EMP.PRE_CHAVE  
, AUX_EMP.DT_REFR  
, AUX_EMP.CD_OPRD_AUX
, AUX_EMP.CD_EMPR_AUX
, aux_emp.CD_DIVISAO // colocado por conta das divisoes da jbs
--, cast(AUX_EMP.CD_PLNO AS INTEGER) AS CD_PLNO
, AUX_EMP.CD_PLNO  AS CD_PLNO
, AUX_EMP.CD_APLC 
, AUX_EMP.CD_EMPR_GRPO 
, AUX_EMP.FL_SEXO 
,cast(AUX_EMP.NR_IDDE AS INTEGER) AS NR_IDDE
, AUX_EMP.NM_FAIX_ETRA 
, AUX_EMP.NM_CATG_USRO
, AUX_EMP.LABEL_OPERADORA
, AUX_EMP.LABEL_EMPRESA
, AUX_EMP.ARH_COD  
, AUX_EMP.PLANO_AON2
-- , AUX_EMP.CODIGO_OPERADORA // NAO TEM NO FASTVIEW_RAW
, AUX_EMP.EMPRESA
, AUX_EMP.FAIXA_ETARIA
, AUX_EMP.GRUPO_ETARIO
, AUX_EMP.CHAVE_PLANO
, AUX_EMP.CHAVE_EMPRESA
, AUX_EMP.NM_OPRD_DP
, AUX_EMP.NM_EMPR_DP
, AUX_EMP.TP_PGTO
, AUX_EMP.PTO_EQLB

, TB_EMPRESAS.CD_OPRD
, TB_EMPRESAS.NM_OPRD
, TB_EMPRESAS.CD_EMPR AS "CD_EMPR_EMP"
, TB_EMPRESAS.NM_EMPR
-- , TB_EMPRESAS.LABEL_EMPRESA
, TB_EMPRESAS.VL_PREM
, TB_EMPRESAS.VL_ACRT
, TB_EMPRESAS.VL_FRNQ
, TB_EMPRESAS.VL_CO_PART_PREM
, TB_EMPRESAS.VL_APRT
, TB_EMPRESAS.VL_PAGO_EVNT
, TB_EMPRESAS.VL_RCBO
, TB_EMPRESAS.VL_CO_PART_UTLZ
, TB_EMPRESAS.VL_IBNR
-- UUID
-- ETL_DT_LOAD_DISCOVERY
-- ETL_SOURCE_FILE_NAME
-- ETL_FILE_NAME_INSIDE_ARCHIVE
-- RUN_ID
,AUX_EMP.ORIGEM

FROM AUX_EMP
LEFT JOIN NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.TB_EMPRESAS 
    ON ( TB_EMPRESAS.CD_OPRD = AUX_EMP.CD_OPRD_AUX) 
    AND (TB_EMPRESAS.CD_EMPR = AUX_EMP.CD_EMPR_AUX)
    
  WHERE 1=1
 AND CHAVE_JOIN is not NULL   
    
    
    ;


-- GRANTS PARA CONCEDER PRIVILÉGIO DE LEITURA AS ROLES QUE O POWERBI UTILIZA
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;

/* FIM DO SCRIPT */