
/*
VIEW: VW_EV_UTLZ
OBJETIVO: MANTER COMPATIBILIDADE COM O POWERBI. REGRAS DE NEGOCIO FORAM IMPLEMENTADAS AS IS
          VIEW ORIGINAL LOCALIZADA DENTRO DO DATABASE NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.FASTVIEW 
          NÃO FORAM FEITAS ALTERACOES NEM REFATORAÇÃO DESSE CODIGO FONTE
AUTOR: DANILO MELO
ALTERAÇOES:
26-03-2024 - VERSÃO INICIAL
 */



create or replace view NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.VW_EV_UTLZ(
	CHAVE_JOIN,
	ID_USRO,
	CD_OPRD,
	CD_EMPR,
	DT_REFR,
	COD_PRESTADOR,
	NM_LCAL_UTLZ,
	NM_EVNT,
	NM_ESPC,
	DS_SRVC,
	CD_USRO,
	NM_USRO,
	DT_INICIO_INTERNACAO,
	DT_ATND,
	VL_PAGO_EVNT2,
	VL_RCBO2,
	VL_CO_PART2,
	QT_SRVC2,
	CD_DIVISAO,
	ARH_COD,
	ID_TER_COMPL_AON,
	ID_PS_AON,
	NM_EVNT2,
	NM_LCAL_UTLZ2,
	CD_SRVC,
	DS_SRVC2,
	CD_TUSS,
	CD_CBHPM,
	PROC_PRINC,
	CATEGORIA,
	TIPO_INTERNACAO,
	REGIME_DIARIA,
	TIPO_ENTRADA,
	GRUPO,
	ETL_DT_LOAD_DISCOVERY,
	EMPRESA,
	CRONICOS,
	CRIPTOGRAFIA_USUARIO,
	LABEL_EVENTOS,
	QTD_SRVC_CONSUL_ELETIVA,
	QTD_SRVC_EXAME,
	QTD_SRVC_TER_SIMPLES,
	QTD_SRVC_AMBULATORIO,
	FAIXA_SINISTRO,
	ANO_REFR,
	ID_INTR_AON,
	SN_PAGO_EVNT,
	SN_RCBO,
	SN_CO_PART_UTLZ,
	VL_PAGO_EVNT_SN,
	VL_RCBO_SN,
	VL_CO_PART_UTLZ_SN,
	NM_REDE_RMBL,
	VL_PAGO_EVNT_SN_PREMIO,
	VL_PAGO_EVNT_SN_SINISTRO,
	VL_RCBO_SN_PREMIO,
	VL_RCBO_SN_SINISTRO,
	VL_CO_PART_UTLZ_SN_PREMIO,
	VL_CO_PART_UTLZ_SN_SINISTRO,
	FLG_MAMOGRAFIA,
	FLG_CANCER_COLORETAL,
	FLG_COLPOCITOLOGIA_ONCOTICA,
	FLG_CARDIOVASCULAR,
	FLG_DIABETES,
	FLG_CANCER_PROSTATA,
	VL_RESUMO_PREMIO,
	VL_RESUMO_SINISTRO
) as 

SELECT 
      EV_UTLZ.CHAVE_JOIN
    , EV_UTLZ.ID_USRO
    , EV_UTLZ.CD_OPRD
    , EV_UTLZ.CD_EMPR
    , TRY_TO_DATE (EV_UTLZ.DT_REFR) DT_REFR
    , EV_UTLZ.COD_PRESTADOR
    , EV_UTLZ.NM_LCAL_UTLZ
    , EV_UTLZ.NM_EVNT
    , EV_UTLZ.NM_ESPC
    , EV_UTLZ.DS_SRVC
    -- , EV_UTLZ.NM_REDE_RMBL
    , EV_UTLZ.CD_USRO
    , EV_UTLZ.NM_USRO
    , TRY_TO_DATE (EV_UTLZ.DT_INICIO_INTERNACAO) AS DT_INICIO_INTERNACAO
    -- , EV_UTLZ.ID_INTR_AON
    , TRY_TO_DATE (EV_UTLZ.DT_ATND) AS DT_ATND
    --, NORMALIZE_MONEY(EV_UTLZ.VL_PAGO_EVNT) VL_PAGO_EVNT2
    , CAST(EV_UTLZ.VL_PAGO_EVNT AS NUMERIC(15,2))  AS VL_PAGO_EVNT2
    , EV_UTLZ.VL_RCBO  as "VL_RCBO2"
    , EV_UTLZ.VL_CO_PART as "VL_CO_PART2"
    , to_number(EV_UTLZ.QT_SRVC) as "QT_SRVC2"
    , EV_UTLZ.CD_DIVISAO
    , EV_UTLZ.ARH_COD
    , EV_UTLZ.ID_TER_COMPL_AON
    , EV_UTLZ.ID_PS_AON
    , EV_UTLZ.NM_EVNT2
    , EV_UTLZ.NM_LCAL_UTLZ2
    , EV_UTLZ.CD_SRVC
    , EV_UTLZ.DS_SRVC2
    , EV_UTLZ.CD_TUSS
    , EV_UTLZ.CD_CBHPM
    , EV_UTLZ.PROC_PRINC
    , EV_UTLZ.CATEGORIA
    , EV_UTLZ.TIPO_INTERNACAO
    , EV_UTLZ.REGIME_DIARIA
    , EV_UTLZ.TIPO_ENTRADA
    -- , EV_UTLZ.CRONICOS
    , EV_UTLZ.GRUPO
    -- , EV_UTLZ.CODIGO_OPERADORA // NAO TEM NO FASTVIEW_RAW
    -- , EV_UTLZ.UUID
    , GETDATE() as ETL_DT_LOAD_DISCOVERY
    -- , EV_UTLZ.ETL_SOURCE_FILE_NAME
    -- , EV_UTLZ.RUN_ID
    , TB_EMPRESAS.LABEL_EMPRESA as EMPRESA
    -- , EV_UTLZ.CD_OPRD_ARQUIVO
    -- , EV_UTLZ.ETL_FILE_NAME_INSIDE_ARCHIVE
    
    , CASE
         WHEN CRONICOS IS NULL THEN 'Não Crônicos'
         ELSE CRONICOS
     END AS "CRONICOS"

    // hash aqui é só pra ocultar o nome do usuario em visualizacoes onde precisa de uma
    // "identificaceo de usuario" por exemplo uma planilha de gastos.
    , HASH(CD_USRO) AS "CRIPTOGRAFIA_USUARIO" //revisar depois que isso nao é uma boa prática

    , CASE
        WHEN NM_EVNT2 = 'EXAME' THEN 'Exame' 
        WHEN NM_EVNT2 = 'EXAMES' THEN 'Exame' 
        WHEN NM_EVNT2 = 'CONSULTAPS' THEN 'Pronto Socorro' // unificado a pedido da Ana Cardoso
        WHEN NM_EVNT2 = 'ATENDIMENTO P.S' THEN 'Pronto Socorro' // unificado a pedido da Ana Cardoso 
        WHEN NM_EVNT2 = 'CONSULTAELETIVA' THEN 'Consulta Eletiva' 
        WHEN NM_EVNT2 = 'AMBULATORIO' THEN 'Ambulatório' 
        WHEN NM_EVNT2 = 'INTERNACAO' THEN 'Internação' 
        WHEN NM_EVNT2 = 'TERAPIA SIMPLES' THEN 'Terapia Simples'
        WHEN NM_EVNT2 = 'TERAPIASIMPLES' THEN 'Terapia Simples'
        WHEN NM_EVNT2 = 'TERAPIA COMPLEXA' THEN 'Terapia Complexa' 
        WHEN NM_EVNT2 = 'TERAPIACOMPLEXA' THEN 'Terapia Complexa' 
        ELSE 'Ambulatório' // alterado de nao identificado para ambulatorio a pedido da Ana Cardoso 
     END AS "LABEL_EVENTOS"

    // CRIACAO DE FLAGS PARA FACILITAR O CALCULO DE qtd_eventos 
    , iff  (LABEL_EVENTOS = 'Consulta Eletiva', to_number(EV_UTLZ.QT_SRVC), 0)  QTD_SRVC_CONSUL_ELETIVA
    , iff  (LABEL_EVENTOS = 'Exame', to_number(EV_UTLZ.QT_SRVC), 0)             QTD_SRVC_EXAME
    , iff  (LABEL_EVENTOS = 'Terapia Simples', to_number(EV_UTLZ.QT_SRVC), 0)   QTD_SRVC_TER_SIMPLES
    , iff  (LABEL_EVENTOS = 'Ambulatório', 1, 0)                                QTD_SRVC_AMBULATORIO
     
     , CASE 
         WHEN VL_PAGO_EVNT2 <= 2500 THEN 'a. R$ 0,01 a 2,5 mil'
         WHEN VL_PAGO_EVNT2 <= 15000 THEN 'b. R$ 2,5 mil a 15 mil'
         WHEN VL_PAGO_EVNT2 <= 50000 THEN 'c. R$ 15 mil a 50 mil'
         WHEN VL_PAGO_EVNT2 <= 100000 THEN 'd. R$ 50 mil a 100 mil'
         ELSE 'e. Acima de R$ 100 mil'
     END AS "FAIXA_SINISTRO"

     --, RIGHT (DT_REFR, 4) AS "ANO_REFR" // tirei a condicao de ([DT_REFR]) <= 2018 then 2018 else Date.Year([DT_REFR]))
     ,YEAR(DT_REFR)  AS "ANO_REFR"
    , CASE // PRECISA DISSO ?
          WHEN ID_INTR_AON IS NULL THEN ''
          ELSE ID_INTR_AON
      END AS "ID_INTR_AON"

    -- , TB_EMPRESAS.CD_OPRD
    -- , TB_EMPRESAS.NM_OPRD
    -- , TB_EMPRESAS.CD_EMPR
    -- , TB_EMPRESAS.NM_EMPR
    -- , TB_EMPRESAS.LABEL_EMPRESA
    -- , TB_EMPRESAS.VL_PREM AS "SN_PREM"
    -- , TB_EMPRESAS.VL_ACRT AS "SN_ACRT" 
    -- , TB_EMPRESAS.VL_FRNQ AS "SN_FRNQ"
    -- , TB_EMPRESAS.VL_CO_PART_PREM AS "SN_CO_PART_PREM"
    -- , TB_EMPRESAS.VL_APRT AS "SN_APRT"
    , TB_EMPRESAS.VL_PAGO_EVNT AS "SN_PAGO_EVNT"
    , TB_EMPRESAS.VL_RCBO AS "SN_RCBO"
    , TB_EMPRESAS.VL_CO_PART_UTLZ AS "SN_CO_PART_UTLZ"

    , CASE 
        WHEN SN_PAGO_EVNT = '0' THEN VL_PAGO_EVNT2 * (0)
        WHEN LEFT (SN_PAGO_EVNT, 1) = '+' THEN VL_PAGO_EVNT2 * (1)
        ELSE VL_PAGO_EVNT2 * (-1)
     END AS "VL_PAGO_EVNT_SN"

    , CASE 
        WHEN SN_RCBO = '0' THEN VL_RCBO2 * (0)
        WHEN LEFT (SN_RCBO, 1) = '+' THEN VL_RCBO2 * (1)
        ELSE VL_RCBO2 * (-1)
     END AS "VL_RCBO_SN"

    , CASE 
        WHEN SN_CO_PART_UTLZ = '0' THEN VL_CO_PART2 * 0
        WHEN LEFT (SN_CO_PART_UTLZ, 1) = '+' THEN VL_CO_PART2 * 1
        ELSE VL_CO_PART2 * (-1)
     END AS "VL_CO_PART_UTLZ_SN"

    , CASE 
        WHEN NM_REDE_RMBL = 'REEMBOLSO' THEN 'Reembolso'
        ELSE 'Rede'
     END AS "NM_REDE_RMBL"


     --- VERIFICANDO AS LETRAS
    , CASE 
        WHEN RIGHT (SN_PAGO_EVNT, 1) = 'p' THEN VL_PAGO_EVNT_SN * (1)
        ELSE VL_PAGO_EVNT_SN * (0)
     END AS "VL_PAGO_EVNT_SN_PREMIO"

    , CASE 
        WHEN RIGHT (SN_PAGO_EVNT, 1) = 's' THEN VL_PAGO_EVNT_SN * (1)
        ELSE VL_PAGO_EVNT_SN * (0)
     END AS "VL_PAGO_EVNT_SN_SINISTRO"


    , CASE 
        WHEN RIGHT (SN_RCBO, 1) = 'p' THEN VL_RCBO_SN * (1)
        ELSE (0)
     END AS "VL_RCBO_SN_PREMIO"

    , CASE 
        WHEN RIGHT (SN_RCBO, 1) = 's' THEN VL_RCBO_SN * (1)
        ELSE (0)
     END AS "VL_RCBO_SN_SINISTRO"
     
    , CASE 
        WHEN RIGHT (SN_CO_PART_UTLZ, 1) = 'p' THEN VL_CO_PART_UTLZ_SN * (1)
        ELSE (0)
     END AS "VL_CO_PART_UTLZ_SN_PREMIO"

    , CASE 
        WHEN RIGHT (SN_CO_PART_UTLZ, 1) = 's' THEN VL_CO_PART_UTLZ_SN * (1)
        ELSE (0)
     END AS "VL_CO_PART_UTLZ_SN_SINISTRO"
     
    //flags de rastreamento
	, iff  (EV_UTLZ.CD_TUSS in ( '40808033', '40808041'), 1, 0)                                                    FLG_MAMOGRAFIA
    , iff  (EV_UTLZ.CD_TUSS in ( '40201082', '40201090' ,'40201350' ,  '40202135' , '40202666' , '40202712' , '41001265' ,
                                '40201171' , '40201180' , '40202682' , '40202690' , '40202720' , '40202739' , '40303136' , 
                                '40303250'), 1, 0)                                                                 FLG_CANCER_COLORETAL
    , iff  (EV_UTLZ.CD_TUSS in ( '40601129', '40601137', '41301099'), 1, 0)                                        FLG_COLPOCITOLOGIA_ONCOTICA
    , iff  (EV_UTLZ.CD_TUSS in ( '40301583', '40301591', '40301605','40302695', '40302547','40302750' ), 1, 0)     FLG_CARDIOVASCULAR
    , iff  (EV_UTLZ.CD_TUSS in ( '40302032', '40302040', '40302709', '40302075', '40302733'), 1, 0)                FLG_DIABETES
    , iff  (EV_UTLZ.CD_TUSS in ( '40316130', '40316149'), 1, 0)                                                    FLG_CANCER_PROSTATA

    
    
    // resumo dos valores 
    , (VL_PAGO_EVNT_SN_PREMIO + VL_RCBO_SN_PREMIO + VL_CO_PART_UTLZ_SN_PREMIO ) AS "VL_RESUMO_PREMIO"
    , (VL_PAGO_EVNT_SN_SINISTRO + VL_RCBO_SN_SINISTRO + VL_CO_PART_UTLZ_SN_SINISTRO) AS "VL_RESUMO_SINISTRO"

           
   
FROM NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.EV_UTLZ
LEFT JOIN NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.TB_EMPRESAS 
    ON ( TB_EMPRESAS.CD_OPRD = EV_UTLZ.CD_OPRD) 
    AND (TB_EMPRESAS.CD_EMPR = EV_UTLZ.CD_EMPR)
;


-- GRANTS PARA CONCEDER PRIVILÉGIO DE LEITURA AS ROLES QUE O POWERBI UTILIZA
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;

/* FIM DO SCRIPT */