
/*
VIEW: VW_EV_PREM
OBJETIVO: MANTER COMPATIBILIDADE COM O POWERBI. REGRAS DE NEGOCIO FORAM IMPLEMENTADAS AS IS
          VIEW ORIGINAL LOCALIZADA DENTRO DO DATABASE NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.FASTVIEW 
          NÃO FORAM FEITAS ALTERACOES NEM REFATORAÇÃO DESSE CODIGO FONTE
AUTOR: DANILO MELO
ALTERAÇOES:
26-03-2024 - VERSÃO INICIAL
 */


create or replace view NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.VW_EV_PREM(
	CHAVE_JOIN,
	DT_REFR,
	CD_OPRD,
	CD_EMPR,
	CD_APLC,
	CD_EMPR_GRPO,
	QT_USRO,
	VL_PREM2,
	VL_ACRT2,
	VL_FRNQ2,
	VL_APRT2,
	VL_CO_PART2,
	ETL_DT_LOAD_DISCOVERY,
	EMPRESA,
	SN_PREM,
	SN_ACRT,
	SN_FRNQ,
	SN_CO_PART_PREM,
	SN_APRT,
	VL_PREM_SN,
	VL_ACRT_SN,
	VL_FRNQ_SN,
	VL_CO_PART_PREM_SN,
	VL_APRT_SN,
	VL_PREM_SN_PREMIO,
	VL_PREM_SN_SINISTRO,
	VL_ACRT_SN_PREMIO,
	VL_ACRT_SN_SINISTRO,
	VL_FRNQ_SN_PREMIO,
	VL_FRNQ_SN_SINISTRO,
	VL_CO_PART_PREM_SN_PREMIO,
	VL_CO_PART_PREM_SN_SINISTRO,
	VL_APRT_SN_PREMIO,
	VL_APRT_SN_SINISTRO,
	VL_RESUMO_PREMIO,
	VL_RESUMO_SINISTRO

) as 

SELECT 
      EV_PREM.CHAVE_JOIN
    ---, TO_DATE (ev_prem.dt_refr, 'dd/mm/YYYY') DT_REFR
     ,TO_DATE (ev_prem.dt_refr) DT_REFR
    , EV_PREM.CD_OPRD
    , EV_PREM.CD_EMPR
    , EV_PREM.CD_APLC
    , EV_PREM.CD_EMPR_GRPO
    , TO_NUMERIC (ev_prem.qt_usro) AS "QT_USRO"
    , EV_PREM.VL_PREM AS "VL_PREM2"
    , EV_PREM.VL_ACRT AS "VL_ACRT2"
    , EV_PREM.VL_FRNQ AS "VL_FRNQ2"
    , EV_PREM.VL_APRT AS "VL_APRT2"
    , EV_PREM.VL_CO_PART AS "VL_CO_PART2"

    -- , EV_PREM.CODIGO_OPERADORA // NAO TEM NO FASTVIEW_RAW
    -- , EV_PREM.UUID
    , GETDATE() AS ETL_DT_LOAD_DISCOVERY
    -- , EV_PREM.ETL_SOURCE_FILE_NAME
    -- , EV_PREM.RUN_ID
    , TB_EMPRESAS.LABEL_EMPRESA as EMPRESA
    -- , EV_PREM.CD_OPRD_ARQUIVO
    -- , EV_PREM.ETL_FILE_NAME_INSIDE_ARCHIVE
    -- , TB_EMPRESAS.CD_OPRD
    -- , TB_EMPRESAS.NM_OPRD
    -- , TB_EMPRESAS.CD_EMPR
    -- , TB_EMPRESAS.NM_EMPR
    -- , TB_EMPRESAS.LABEL_EMPRESA
    , TO_CHAR (TB_EMPRESAS.VL_PREM) AS "SN_PREM"
    , TO_CHAR (TB_EMPRESAS.VL_ACRT) AS "SN_ACRT" 
    , TO_CHAR (TB_EMPRESAS.VL_FRNQ) AS "SN_FRNQ"
    , TO_CHAR (TB_EMPRESAS.VL_CO_PART_PREM) AS "SN_CO_PART_PREM"
    , TO_CHAR (TB_EMPRESAS.VL_APRT) AS "SN_APRT"


    -- , TB_EMPRESAS.VL_PAGO_EVNT
    -- , TB_EMPRESAS.VL_RCBO
    -- , TB_EMPRESAS.VL_CO_PART_UTLZ
    -- , TB_EMPRESAS.VL_IBNR

    , CASE 
        WHEN SN_PREM = '0' THEN VL_PREM2 * (0)
        WHEN LEFT (SN_PREM, 1) = '+' THEN VL_PREM2 * (1)
        ELSE VL_PREM2 * (-1)
     END AS "VL_PREM_SN"


    , CASE 
        WHEN SN_ACRT = '0' THEN VL_ACRT2 * (0)
        WHEN LEFT (SN_ACRT, 1) = '+' THEN VL_ACRT2 * (1)
        ELSE VL_ACRT2 * (-1)
     END AS "VL_ACRT_SN"

    , CASE
        WHEN SN_FRNQ = '0' THEN VL_FRNQ2 * (0)
        WHEN LEFT (SN_FRNQ, 1) = '+' THEN VL_FRNQ2 * (1)
        ELSE VL_FRNQ2 * (-1)
     END AS "VL_FRNQ_SN"


    , CASE 
        WHEN SN_CO_PART_PREM = '0' THEN VL_CO_PART2 * (0)
        WHEN LEFT (SN_CO_PART_PREM, 1) = '+' THEN VL_CO_PART2 * (1)
        ELSE VL_CO_PART2 * (-1)
     END AS "VL_CO_PART_PREM_SN"


    , CASE 
        WHEN SN_APRT = '0' THEN VL_APRT2 * (0)
        WHEN LEFT (SN_APRT, 1) = '+' THEN VL_APRT2 * (1)
        ELSE VL_APRT2 * (-1)
     END AS "VL_APRT_SN"

--- VERIFICANDO AS LETRAS
    , CASE 
        WHEN RIGHT (SN_PREM, 1) = 'p' THEN VL_PREM_SN * (1)
        ELSE VL_PREM_SN * (0)
     END AS "VL_PREM_SN_PREMIO"

    , CASE 
        WHEN RIGHT (SN_PREM, 1) = 's' THEN VL_PREM_SN * (1)
        ELSE VL_PREM_SN * (0)
     END AS "VL_PREM_SN_SINISTRO"


    , CASE 
        WHEN RIGHT (SN_ACRT, 1) = 'p' THEN VL_ACRT_SN * (1)
        ELSE (0)
     END AS "VL_ACRT_SN_PREMIO"

    , CASE 
        WHEN RIGHT (SN_ACRT, 1) = 's' THEN VL_ACRT_SN * (1)
        ELSE (0)
     END AS "VL_ACRT_SN_SINISTRO"
     
    , CASE 
        WHEN RIGHT (SN_FRNQ, 1) = 'p' THEN VL_FRNQ_SN * (1)
        ELSE (0)
     END AS "VL_FRNQ_SN_PREMIO"

    , CASE 
        WHEN RIGHT (SN_FRNQ, 1) = 's' THEN VL_FRNQ_SN * (1)
        ELSE (0)
     END AS "VL_FRNQ_SN_SINISTRO"

    , CASE 
        WHEN RIGHT (SN_CO_PART_PREM, 1) = 'p' THEN VL_CO_PART_PREM_SN * (1)
        ELSE (0)
     END AS "VL_CO_PART_PREM_SN_PREMIO"

    , CASE 
        WHEN RIGHT (SN_CO_PART_PREM, 1) = 's' THEN VL_CO_PART_PREM_SN * (1)
        ELSE (0)
     END AS "VL_CO_PART_PREM_SN_SINISTRO"
     
    , CASE 
        WHEN RIGHT (SN_APRT, 1) = 'p' THEN VL_APRT_SN * (1)
        ELSE (0)
     END AS "VL_APRT_SN_PREMIO"

    , CASE 
        WHEN RIGHT (SN_APRT, 1) = 's' THEN VL_APRT_SN * (1)
        ELSE (0)
     END AS "VL_APRT_SN_SINISTRO"
     

    , VL_PREM_SN_PREMIO + VL_ACRT_SN_PREMIO +VL_FRNQ_SN_PREMIO + VL_CO_PART_PREM_SN_PREMIO + VL_APRT_SN_PREMIO  AS "VL_RESUMO_PREMIO"
    , VL_PREM_SN_SINISTRO + VL_ACRT_SN_SINISTRO +VL_FRNQ_SN_SINISTRO + VL_CO_PART_PREM_SN_SINISTRO + VL_APRT_SN_SINISTRO  AS "VL_RESUMO_SINISTRO"



FROM NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.EV_PREM


LEFT JOIN NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.TB_EMPRESAS  TB_EMPRESAS
    ON ( TB_EMPRESAS.CD_OPRD = EV_PREM.CD_OPRD) 
    AND (TB_EMPRESAS.CD_EMPR = EV_PREM.CD_EMPR)    
;

-- GRANTS PARA CONCEDER PRIVILÉGIO DE LEITURA AS ROLES QUE O POWERBI UTILIZA
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;

/* FIM DO SCRIPT */