





create or replace view NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.VW_TB_USRO
/*
VIEW: VW_TB_USRO
OBJETIVO: MANTER COMPATIBILIDADE COM O POWERBI. REGRAS DE NEGOCIO FORAM IMPLEMENTADAS AS IS
          VIEW ORIGINAL LOCALIZADA DENTRO DO DATABASE NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.FASTVIEW 
          NÃO FORAM FEITAS ALTERACOES NEM REFATORAÇÃO DESSE CODIGO FONTE
AUTOR: DANILO MELO
ALTERAÇOES:
26-03-2024 - VERSÃO INICIAL
 */


(
	CD_OPRD,
	ID_USRO,
	CD_USRO2,
	NM_USRO,
	DT_NSCM,
	FL_SEXO,
	CPF_USRO,
	CD_MATR,
	CD_MATR_ESPC,
	ARH_COD,
	DT_ADMS,
	DT_EXCL,
	DT_UREF,
	STATUS,
  CD_EMPR,
	EMPRESA,
	QT_DIAS_PLANO,
	FLG_RAST_TEMPO_PLANO,
	IDADE
) as 

SELECT 
      LTRIM (CD_OPRD, '0') AS CD_OPRD
    -- , CD_OPRD_ARQUIVO
    , ID_USRO
    , CD_USRO2
    , NM_USRO
    , TRY_TO_DATE (DT_NSCM) DT_NSCM 
    , FL_SEXO
    , CPF_USRO
    , CD_MATR
    , CD_MATR_ESPC
    , ARH_COD
    , TRY_TO_DATE (DT_ADMS) DT_ADMS
    , TRY_TO_DATE (DT_EXCL) DT_EXCL
   -- , TRY_TO_DATE (DT_UREF) DT_UREF
    ,   DT_UREF as DT_UREF
    , STATUS
    , CD_EMPR
    , NOME_EMPRESA as EMPRESA
    -- , CODIGO_OPERADORA  // NAO TEM NO FASTVIEW_RAW  
    , DATEDIFF(day, TRY_TO_DATE (DT_ADMS) , current_date) QT_Dias_plano
    , iff ( DATEDIFF(day, TRY_TO_DATE (DT_ADMS ), current_date)  > 365 , 1, 0) FLG_RAST_TEMPO_PLANO
    , (DATEDIFF(YEAR, TRY_TO_DATE (DT_NSCM), current_date)  )  IDADE
   -- , UUID
   -- , ETL_DT_LOAD_DISCOVERY
   -- , ETL_SOURCE_FILE_NAME
   -- , RUN_ID
   -- , ETL_FILE_NAME_INSIDE_ARCHIVE
   -- , NOBS
FROM 
    NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.TB_USRO

;


-- GRANTS PARA CONCEDER PRIVILÉGIO DE LEITURA AS ROLES QUE O POWERBI UTILIZA
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;

/* FIM DO SCRIPT */