create or replace view NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.VW_TB_UTLZ(
	CHAVE_JOIN,
	PRE_CHAVE,
	ID_USRO,
	CD_OPRD,
	CD_EMPR,
	DT_REFR,
	COD_PRESTADOR,
	NM_LCAL_UTLZ,
	NM_EVNT,
	NM_ESPC,
	CD_SRVC,
	DS_SRVC,
	NM_REDE_RMBL,
	CD_USRO,
	NM_USRO,
	DT_INICIO_INTERNACAO,
	ID_INTR_AON,
	DT_ATND,
	VL_PAGO_EVNT,
	VL_RCBO,
	VL_CO_PART,
	QT_SRVC,
	CD_DIVISAO,
	ID_TER_COMPL_AON,
	ID_PS_AON,
	NM_EVNT2,
	NM_LCAL_UTLZ2,
	DS_SRVC_2,
	CD_TUSS,
	CD_CBHPM,
	PROC_PRINC,
	CATEGORIA,
	TIPO_INTERNACAO,
	REGIME_DIARIA,
	TIPO_ENTRADA,
	CRONICOS,
	GRUPO
) as 

WITH TABELA_UTILIZACAO as(
SELECT DISTINCT 

--'TBD' AS CHAVE_JOIN
--,
'TBD' AS ID_USRO
, 9 as CD_OPRD
,EMPRESAS.CODIGO_EMPRESA CD_EMPR
,CAST(CONCAT(YEAR(DATA_REFERENCIA) , '-' , MONTH(DATA_REFERENCIA), '-01' ) AS DATE) AS DT_REFR
,CODIGO_CNPJ_PRESTADOR as COD_PRESTADOR
,NOME_PRESTADOR as NM_LCAL_UTLZ
,NOME_EVENTO as NM_EVNT
,CONCAT( DESCRICAO_TIPO_CATEGORIA_SINISTRO , '_', DESCRICAO_POSICAO_PRESTADOR) AS NM_ESPC
,CODIGO_PROCEDIMENTO AS CD_SRVC
,DESCRICAO_PROCEDIMENTO AS DS_SRVC
,TIPO_ATENDIMENTO AS NM_REDE_RMBL
,A.CODIGO_BENEFICIARIO as CD_USRO -- TODO: NOME TRATADO MAIS DATA DE NASCIMENTO FORMATO JULIANO
,CADASTRO.NOME_BENEFICIARIO AS NM_USRO -- TODO: DESCOBRIR COMO TRATAR O NOME DO USUARIO
,INICIO_INTERNACAO AS DT_INICIO_INTERNACAO
,CHAVE_INTERNACAO_AON AS ID_INTR_AON
, DATA_PROCEDIMENTO AS DT_ATND
,VALOR_PAGO AS VL_PAGO_EVNT
, 0 AS VL_RCBO
, VALOR_COPARTICIPACAO  AS VL_CO_PART
, QUANTIDADE_PROCEDIMENTO AS QT_SRVC
, '00' AS CD_DIVISAO -- SOMENTE PARA JBS E FEMSA
, CHAVE_TERAPIA_COMPLEXA_AON AS ID_TER_COMPL_AON -- TBD TODOS OS CAMPOS ESTAO VINDO NULOS
, CHAVE_PRONTO_SOCORRO_AON AS ID_PS_AON
, NM_EVNT2 AS NM_EVNT2 
, 'TBD' AS NM_LCAL_UTLZ2 -- TODO: VERIFICAR QUAL A TABELA DE-PARA
, DS_SRVC_ORIGINAL AS DS_SRVC_2
, COD_TUSS AS CD_TUSS
, COD_CBHPM AS CD_CBHPM
, PROC_PRINC AS PROC_PRINC
, CATEGORIA AS CATEGORIA
, TIPO_INTERNACAO AS TIPO_INTERNACAO
, REGIME_DIARIA AS REGIME_DIARIA
, TIPO_ENTRADA_INTERNACAO AS TIPO_ENTRADA
, CRONICO AS CRONICOS
, GRUPO AS GRUPO
, PLANOS.CD_PLNO
, CODIGO_CONTRATO as CD_APLC
, CASE 
    WHEN SUBSTR(CODIGO_LOCAL_EMPRESA_OPERADORA, 0,1) = '0' THEN SUBSTR(CODIGO_LOCAL_EMPRESA_OPERADORA, 2,5)
    ELSE CODIGO_LOCAL_EMPRESA_OPERADORA
END AS CD_EMPR_GRPO -- ZERO a ESQUERDA tratado
 , DESCRICAO_GENERO AS FL_SEXO
 , IDADE_BENEFICIARIO as NR_IDDE
,CASE
    WHEN IDADE_BENEFICIARIO IS NULL THEN 'N/C'
    WHEN IDADE_BENEFICIARIO <= 18 THEN '00 a 18'
    WHEN IDADE_BENEFICIARIO <= 23 then '19 a 23'
    WHEN IDADE_BENEFICIARIO <= 28 then '24 a 28'
    WHEN IDADE_BENEFICIARIO <= 33 then '29 a 33'
    WHEN IDADE_BENEFICIARIO <= 38 then '34 a 38'
    WHEN IDADE_BENEFICIARIO <= 43 then '39 a 43'
    WHEN IDADE_BENEFICIARIO <= 48 then '44 a 48' 
    WHEN IDADE_BENEFICIARIO <= 53 then '49 a 53'
    WHEN IDADE_BENEFICIARIO <= 58 then '54 a 58'
    WHEN IDADE_BENEFICIARIO >= 59 then '59 ou +'
    ELSE 'N/C'
END 
AS NM_FAIX_ETRA
,CASE
    WHEN DESCRICAO_ELEGIBILIDADE = 'TITULAR' THEN 'T'
    WHEN DESCRICAO_ELEGIBILIDADE = 'DEPENDENTE' THEN 'D'
    WHEN DESCRICAO_ELEGIBILIDADE IS NOT NULL THEN 'D'
END 
AS NM_CATG_USRO
,PLANOS.OBSERVACAO as PLANO_AON_2
FROM NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.SULAMERICA_CLASSIFICACAO  A 


LEFT JOIN NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.AUXILIAR.EMPRESAS  EMPRESAS
on A.CODIGO_CONTRATO = EMPRESAS.CODIGO_APOLICE


LEFT JOIN  NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.AUXILIAR.PLANOS PLANOS
ON A.CODIGO_PLANO = PLANOS.CD_PLNO
AND EMPRESAS.CODIGO_EMPRESA  = PLANOS.CD_EMPR

LEFT JOIN  (select distinct CODIGO_BENEFICIARIO, NOME_BENEFICIARIO from NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.DATABRICKS_SILVER.CADASTRO_SULAMERICA) CADASTRO
ON  A.CODIGO_BENEFICIARIO = CADASTRO.CODIGO_BENEFICIARIO

WHERE 1=1
--and  NOME_LOCAL_EMPRESA_OPERADORA like '%THOMAS%'

--limit 20
)


SELECT 
HASH (
    CONCAT(
        DT_REFR
        ,CD_OPRD
        ,CD_EMPR
        ,CD_PLNO
        ,CD_APLC
        ,CD_EMPR_GRPO
        ,FL_SEXO
        ,NR_IDDE
        ,NM_FAIX_ETRA
        ,NM_CATG_USRO
        ,CD_DIVISAO
        ,PLANO_AON_2
    )


) as CHAVE_JOIN
, CONCAT(
    DT_REFR
    ,CD_OPRD
    ,CD_EMPR
    ,CD_PLNO
    ,CD_APLC
    ,CD_EMPR_GRPO
    ,FL_SEXO
    ,NR_IDDE
    ,NM_FAIX_ETRA
    ,NM_CATG_USRO
    ,CD_DIVISAO
    ,PLANO_AON_2
) AS PRE_CHAVE
, ID_USRO
, CD_OPRD
, CD_EMPR
, DT_REFR
, COD_PRESTADOR
, NM_LCAL_UTLZ
, NM_EVNT
, NM_ESPC
, CD_SRVC
, DS_SRVC
, NM_REDE_RMBL
, CD_USRO
, NM_USRO
, DT_INICIO_INTERNACAO
, ID_INTR_AON
, DT_ATND
, VL_PAGO_EVNT
, VL_RCBO
, VL_CO_PART
, QT_SRVC
, CD_DIVISAO
, ID_TER_COMPL_AON
, ID_PS_AON
, NM_EVNT2
, NM_LCAL_UTLZ2
, DS_SRVC_2
, CD_TUSS
, CD_CBHPM
, PROC_PRINC
, CATEGORIA
, TIPO_INTERNACAO
, REGIME_DIARIA
, TIPO_ENTRADA
, CRONICOS
, GRUPO

from TABELA_UTILIZACAO;