
/*
VIEW: VW_TB_USRO_CAD
OBJETIVO: MANTER COMPATIBILIDADE COM O POWERBI. REGRAS DE NEGOCIO FORAM IMPLEMENTADAS AS IS
          VIEW ORIGINAL LOCALIZADA DENTRO DO DATABASE NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.FASTVIEW 
          NÃO FORAM FEITAS ALTERACOES NEM REFATORAÇÃO DESSE CODIGO FONTE
AUTOR: DANILO MELO
ALTERAÇOES:
26-03-2024 - VERSÃO INICIAL
 */

create or replace view NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.VW_TB_USRO_CAD(
	CD_OPRD_ARQUIVO,
	CD_OPRD,
	ID_USRO,
	CHAVE_JOIN,
	ARH_COD,
	UTLZ,
	EMPRESA
) as 
select
      CD_OPRD_ARQUIVO
    , LTRIM ( CD_OPRD_ARQUIVO, '0') AS CD_OPRD
    , ID_USRO
    , CHAVE_JOIN
    , ARH_COD
    , UTLZ
    , EMPRESA
    -- , UUID
    -- , ETL_DT_LOAD_DISCOVERY
    -- , ETL_SOURCE_FILE_NAME
    -- , RUN_ID
    -- , ETL_FILE_NAME_INSIDE_ARCHIVE
FROM 
    NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD.TB_USRO_CAD
;

-- GRANTS PARA CONCEDER PRIVILÉGIO DE LEITURA AS ROLES QUE O POWERBI UTILIZA
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE NONPROD_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;
GRANT ALL PRIVILEGES ON ALL views IN SCHEMA NONPROD_BRAZILHEALTHANALYTICS_BRADESCO.GOLD to ROLE nonprod_analyst;

/* FIM DO SCRIPT */